WebApplication1/Models/Models/Model.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
    }
}

WebApplication1/Models/Models/Model.Designer.cs
// 已啟用模型 'C:\Users\student\Documents\src\WebApplication1\Models\Models\Model.edmx' 的 T4 程式碼產生。
// 若要啟用舊版程式碼產生，請將 [程式碼產生策略] 設計工具屬性的值
//變更為 [舊版 ObjectContext]。當模型在設計工具中開啟時，這個屬性便可
//以在 [屬性] 視窗中使用。

// 如果尚未產生任何內容和實體類型，可能是因為您建立了空的模型，但
//尚未選擇要使用的 Entity Framework 版本。若要為您的模型產生內容類別和
//實體類型，請在設計工具中開啟模型，以滑鼠右鍵按一下設計工具介面並
//選取 [從資料庫更新模型]、[由模型產生資料庫] 或 [加入程式碼產生
//項目]。

WebApplication1/Models/Models/Model.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

WebApplication1/Models/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
    }
}

WebApplication1/Models/Models/Model1.Designer.cs
// 已啟用模型 'C:\Users\student\Documents\src\WebApplication1\Models\Models\Model1.edmx' 的 T4 程式碼產生。
// 若要啟用舊版程式碼產生，請將 [程式碼產生策略] 設計工具屬性的值
//變更為 [舊版 ObjectContext]。當模型在設計工具中開啟時，這個屬性便可
//以在 [屬性] 視窗中使用。

// 如果尚未產生任何內容和實體類型，可能是因為您建立了空的模型，但
//尚未選擇要使用的 Entity Framework 版本。若要為您的模型產生內容類別和
//實體類型，請在設計工具中開啟模型，以滑鼠右鍵按一下設計工具介面並
//選取 [從資料庫更新模型]、[由模型產生資料庫] 或 [加入程式碼產生
//項目]。

WebApplication1/Models/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

WebApplication1/Models/Models/Users.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool Gender { get; set; }
    }
}

WebApplication1/Areas/admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Areas.admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/BMIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    public class BMIController : Controller
    {
        // GET: BMI
        public ActionResult Index()
        {
            return View(new BMIData());
        }

        [HttpPost]
        public ActionResult Index(BMIData data)
        {
            if (ModelState.IsValid) {
                if (data.Height < 50 || data.Height > 200)
                {
                    ViewBag.HeightError = "身高請輸入50~200的數值";
                }
                if (data.Weight < 30 || data.Weight > 150)
                {
                    ViewBag.WeightError = "體重請輸入50~200的數值";
                }
                float m_height = data.Height / 100;
                float BMI = data.Weight / (m_height * m_height);
                var level = "";
            }
            return View(data);
        }
        
        
    }

}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Controllers/ScoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class ScoreController : Controller
    {
        // GET: Score
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(float score)
        {


            string code = "";
            if (score >= 0 && score < 20)
            {
                code = "E";
            }
            else if (20 <= score && score <= 39)
            {
                code = "D";
            }
            else if (40 <= score && score <= 59)
            {
                code = "C";
            }
            else if (60 <= score && score <= 79)
            {
                code = "B";
            }
            else if (80 <= score && score <= 100)
            {
                code = "A";
            }

            ViewBag.Score = score;
            ViewBag.Code = code;
            return View();
        }

    }
}

WebApplication1/Controllers/abcdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class abcdController : Controller
    {
        // GET: abcd
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(float score)
        {
            
            
            string code= "";
            if (score >= 0 && score < 20)
            {
                code = "E";
            }
            else if (20<= score && score <= 39)
            {
                code = "D";
            }
            else if (40 <= score && score <= 59)
            {
                code = "C";
            }
            else if (60 <= score && score <= 79)
            {
                code = "B";
            }
            else if (80 <= score && score <= 100)
            {
                code = "A";
            }
            
            ViewBag.score = score;
            ViewBag.code = code;
            return View();
        }

    }
}

WebApplication1/Areas/admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

WebApplication1/Areas/admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("admin", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/BMI/Index.cshtml
@model WebApplication1.ViewModel.BMIData    
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h2>admin</h2>
<form method="post" action="@Url.Action("Index")">
    身高 @Html.TextBoxFor(a => a.Height)公分 @ViewBag.HeightError <br />
    體重 @Html.TextBoxFor(a => a.Weight)公斤 @ViewBag.WeightError <br />
    <input type="submit" value="送出" />
</form>
<br />

計算結果： @Model.BMI <br />
等級： @Model.Level

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
<form method="post">
    姓氏 <input type="text" name="lastname" value="" />
    名字 <input type="text" name="firstname" value="" />
    <br />
    電子郵件 <input type="text" name="email" value="" />
    <br />
    密碼 <input type="password" name="password" value="" />
    <br />
    生日
    <select name="year">
        <option value="2017">2017</option>
        <option value="2016">2016</option>
    </select>年
    <select name="month">
        <option value="1">1月</option>
        <option value="2">2月</option>
    </select>月
    <select name="day">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
    </select>日

    <br />
    性別
    <input type="radio" name="sex" value="1"> 男生
    <input type="radio" name="sex" value="0"> 女生

    <br />
    <input type="submit" value="送出" />
</form>
@using (Html.BeginForm("About", "Home", FormMethod.Post))
{
    <span>姓名</span> @Html.TextBox("username")
    <br />
    <span>Email</span> @Html.TextBox("email")
    <br />
    <span>密碼</span> @Html.Password("pwd")
} (edited)

@{
    string[] data = { "蘋果", "香蕉", "荔枝", "鳳梨", "西瓜" };
}
<ol>
    @foreach (var item in data)
    {
        <li>
            @item
        </li>
    }
</ol>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<form  action="/Score/Index" method="post">
    <h1>分數代碼查詢</h1>
    請輸入分數： 
    <input type="text" name="score" value="" /><br />

    <input type="submit" value="查詢" />
</form>
<br />
查詢結果<br>
分數： @ViewBag.score <br />
代碼： @ViewBag.code

WebApplication1/Views/Score/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<form action="/Score/Index" method="post">
    <h1>分數代碼查詢</h1>
    請輸入分數：
    <input type="text" name="score" value="" /><br />

    <input type="submit" value="查詢" />
</form>
<br />
查詢結果<br>
分數： @ViewBag.score <br />
代碼： @ViewBag.code

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                    <li>@Html.ActionLink("BMI計算", "Index", "BMI")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>